#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2017-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # file manager plugins supported in SpaceVim:
    # - vimfiler (default)
    # - nerdtree
    # - defx
    filemanager = "nerdtree"
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "OceanicNext"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_display_mode = true
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    enable_vimfiler_gitstatus = true
		# Enable bootstarp scripts
    bootstrap_after = "myconfig#after"
    automatic_update = true
    pymode_python = "python3"

[[layers]]
  name = "default"

# https://spacevim.org/layers/sudo/
[[layers]]
  name = "sudo"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "cycle"

[[layers]]
  name = 'git'

[[layers]]
  name = 'unite'

[[layers]]
  name = 'tools'

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "ui"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#groovy"

[[custom_plugins]]
  name = 'Shougo/deoplete.nvim'
  merged = 0

[[custom_plugins]]
  name = 'Xuyuanp/nerdtree-git-plugin'
  merged = 0

# add custom_plugins: https://github.com/mhartington/oceanic-next
[[custom_plugins]]
  name = "mhartington/oceanic-next"
  merged = 0

[[layers]]
  name = "colorscheme"
