#!/usr/bin/env bash

# Create a new directory and enter it
function mk() {
  mkdir -p "$@" && cd "$@"
}

function run() {
  make $@ && $@
}

# Determine size of a file or total size of a directory
function fs() {
	if du -b /dev/null > /dev/null 2>&1; then
		local arg=-sbh;
	else
		local arg=-sh;
	fi
	if [[ -n "$@" ]]; then
		du $arg -- "$@";
	else
		du $arg .[^.]* ./*;
	fi;
}

case "$OSTYPE" in
    cygwin*)
        alias open="cmd /c start"
        ;;
    linux*)
        alias start="xdg-open"
        alias open="xdg-open"
        ;;
    darwin*)
        alias start="open"
        ;;
esac

# `s` with no arguments opens the current directory in Sublime Text, otherwise
# opens the given location
function s() {
	if [ $# -eq 0 ]; then
		subl .;
	else
		subl "$@";
	fi;
}

# `v` with no arguments opens the current directory in Vim, otherwise opens the
# given location
function v() {
	if [ $# -eq 0 ]; then
		vim .;
	else
		vim "$@";
	fi;
}

# `o` with no arguments opens the current directory, otherwise opens the given
# location
function o() {
	if [ $# -eq 0 ]; then
		open .;
	else
		open "$@";
	fi;
}

# Create .gitignore files https://www.gitignore.io/docs#-use-command-line
function gi() {
        curl -L -s https://www.gitignore.io/api/$@ ;
}

# Highlight manpages syntax
man() {
  /usr/bin/man $* | \
    col -b | \
    vim -R -c 'set ft=man nomod nolist' -
}

# https://askubuntu.com/questions/1196742/how-can-i-use-kazam-screencaster-in-terminal
# - use Super+Ctrl+p to Pause/Resume recording
# - and Super+Ctrl+f to stop recording
function kz () { 
 kazam --silent &> /dev/null & 
 sleep 1 
 xdotool key 'Super+Ctrl+r'; 
 echo "
 - use Super+Ctrl+p to Pause/Resume recording\n
 - and Super+Ctrl+f to stop recording\n
 "
}
