# Run zsh via antigen
source ~/.antigen.zsh

source ~/dotfiles/zsh/aliases
source ~/dotfiles/zsh/functions
source ~/dotfiles/zsh/cheatsheet.sh

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/projects
export VIRTUALENVWRAPPER_PYTHON=$(which python3)
export LANG=en_US.UTF-8
source /usr/local/bin/virtualenvwrapper.sh

# pyenv settings
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# nvm settings
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle tmux
antigen bundle common-aliases
antigen bundle docker-compose
antigen bundle docker-machine
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle akarzim/zsh-docker-aliases

# Load the theme.
# antigen theme denysdovhan/spaceship-prompt
antigen theme ys

# SpaceShip-prompt Customize
# https://medium.com/@caulfieldOwen/youre-missing-out-on-a-better-mac-terminal-experience-d73647abf6d7
SPACESHIP_PROMPT_ADD_NEWLINE="true"
# SPACESHIP_CHAR_PREFIX="\uf296"
# SPACESHIP_CHAR_SYMBOL=" \uf0e7"
# SPACESHIP_CHAR_PREFIX="\uf0d0"
# SPACESHIP_CHAR_SYMBOL=" ✨"
SPACESHIP_CHAR_SYMBOL="\uf0d0" 
SPACESHIP_CHAR_SUFFIX=(" ")
SPACESHIP_CHAR_COLOR_SUCCESS="yellow"
SPACESHIP_PROMPT_DEFAULT_PREFIX="$USER "
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW="true"
SPACESHIP_USER_SHOW="true"

# Tell Antigen that you're done.
antigen apply
export PATH="/usr/local/opt/openssl/bin:$PATH"

bindkey -v

clear && screenfetch
