# Run zsh via antigen
source ~/antigen.zsh

source ~/dotfiles/zsh/nyancat
source ~/dotfiles/zsh/aliases
source ~/dotfiles/zsh/functions

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/projects
source /usr/local/bin/virtualenvwrapper.sh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles from the default repo (robbyrussell's oh-my-zsh).
antigen bundle git
antigen bundle pip
antigen bundle tmux
antigen bundle common-aliases
antigen bundle docker-compose
antigen bundle docker-machine
antigen bundle command-not-found

# Syntax highlighting bundle.
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle akarzim/zsh-docker-aliases

# Load the theme.
antigen theme denysdovhan/spaceship-prompt

# Tell Antigen that you're done.
antigen apply
